FROM ubuntu

RUN apt update

RUN apt -y install python3-dev python3-pip

RUN pip install waitress flask joblib scikit-learn Image

COPY src/ /src/
COPY resources/ /resources/

WORKDIR /src

CMD ["python3", "rest_api.py"]

# Build with: docker build -f dockerfile -t mnist_knn_app_ubuntu .

# Run with: docker run -it -p 5100:5030 -v C:\test_mnist_images:/input_images mnist_knn_app_ubuntu

# JSON Input: {"input_folder" : "/input_images/"}